[[inputs.kube_inventory]]
  ## URL for the Kubernetes API
  url = "$MASTER_VIP_URL"
  ## Namespace to use. Set to "" to use all namespaces.
  namespace = "$PLATFORM_NAMESPACE"
  response_timeout = "15s"
  resource_include = $RESOURCE_INCLUDE
  bearer_token = "/run/secrets/kubernetes.io/serviceaccount/token"
  tls_ca = "/run/secrets/kubernetes.io/serviceaccount/ca.crt"

[[aggregators.kubernetes_component]]
  period = "60s"
  drop_original = true
  reset_time = $RESET_TIME
  notify_times = $NOTIFY_TIMES

[[inputs.global_kubernetes]] # 共享 kubernetes client, 不主动采集数据
    k8s_url = "$MASTER_VIP_URL"
    k8s_timeout = "${K8S_TIMEOUT:20s}"
    k8s_bearer_token = "${K8S_BEARER_TOKEN:/run/secrets/kubernetes.io/serviceaccount/token}"
    [inputs.global_kubernetes.k8s_client_config]
        tls_ca = "${K8S_TLS_CA:/run/secrets/kubernetes.io/serviceaccount/ca.crt}"