[[inputs.termiuns_sidecar]]
    interval = "1m"
    metric_name = "sidecar"
    urls = ["http://$HOST_IP:34903/metrics"]

[[inputs.global_kubernetes]] # 共享 kubernetes client, 不主动采集数据
    k8s_url = "$EDGE_MASTER_VIP_URL"
    k8s_timeout = "${K8S_TIMEOUT:20s}"
    k8s_bearer_token = "${K8S_BEARER_TOKEN:/run/secrets/kubernetes.io/serviceaccount/token}"
    [inputs.global_kubernetes.k8s_client_config]
        tls_ca = "${K8S_TLS_CA:/run/secrets/kubernetes.io/serviceaccount/ca.crt}"

[[processors.add_kubernetes_metadata]]
    order = 1
    labels = ["openyurt.io/is-edge-worker", "apps.openyurt.io/nodepool"]

[[processors.rename]]
    order = 2
    [[processors.rename.replace]]
        tag = "k8s_node_label_openyurt.io/is-edge-worker"
        dest = "is_edge_node"
    [[processors.rename.replace]]
        tag = "k8s_node_label_apps.openyurt.io/nodepool"
        dest = "edge_site"